PHISHNET_API_KEY = "9D88CF107498984DD3CE"

[GSPREAD_SERVICE_ACCOUNT]
type                        = "service_account"
project_id                  = "barnswallowfantasy"
private_key_id              = "c5f9301af9c1ffaf9b212d1bfdee70697dce40f5"
private_key                 = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC49hDLbYq6YIQl
iiftiu6UEhiJPo9lnBhyq4KIZIj9YLxf9HNpyQ81xR31xwD0ZgS7XerZu0kAvNFp
nRKdmPuqSq37+a8KBp4jU+Yx62b2DZSGrskl02JM9R3uqtLCgwYxXX7DJ6I8jrJN
1o7GdlQlg40qI4MgFTlVW0VOX49d2we1ujKumYWAcWFQUlaR+CsOFRLAPHQAjQaM
+WaRJVQQTcMQOqDZmjmm23NEmtw9QyY2jCF7aT/YOToGCPQOxh5VWMFtjvQh0KLg
m+IqMbH7jBl09KpD44u7HstOSkCx1CB2GPNX8iofEuDt+p7v7y1XBxZLGYiHiwti
ONTjJLtNAgMBAAECggEAGfaUifHBAQOOWTSpASu47LkTj6Rj/afpOKOBqcKvBh4/
oxqN3uIVy/71Ayyhoiz16hU3Y8Pp7fwTS0d8tvmkDhX4kT/NxdMC/MOIsyYvqEdk
u3kqjDA9gr7/qiJ5fktlIaXVpvBX0jdXqRx+ozY1/qQWOz2L6QOBrk0nD+bTGaHp
vXky7CUPgFTLJN2pyIyknnnALAnMc9Sipnc0T9yardDTQamyxBEu8/ULPNR15QNi
VBR9q9hCeVzOPe6HPxalHyIycUzC00yRtZ+rcz9b2/wOsQ4lauf0lVqHwThn5yH1
PY8FaeaXEAGcg0RjfGEWNHEt35y9P3fcVFja8+1y4QKBgQDcCivN80uwM+xeJtqF
RnjgsCp3HrDkK2HnLfyWY4NBpbxmoh+8f5ghS7vLBhQruhCIcQVqWdqgCKs7ubqs
N/PKrkpJz8xulvqJ/7bjTTMv8SPP2/SgA3lFBPtlySZTZ/58rIM73UiWup8CqqNh
n5J0VLR4IvdyxyqfawYtpBe+HQKBgQDXME86TIXYmXf2PtvhptDHaCkeV9g2lgLi
ZeEBdYcs6Q7cjHdZ5uMGaspqdOG/w0NUx+H4DrSyjJuK4GIBY+yo5QibgAGos2lx
r1ZAeBi7hd3o6+Og+nXIgTT+l70WKoS4fZ9DKXYcEKGL88/vRyKk5x/dijjoUTA+
bxLzBuIq8QKBgQDS98GGBdW0zCO9Jb1v+OBedSlR6pApQ9rrXvEFc8XeBDy9noWV
IjTG/6i/AEYIoq3FU6+ghyQROh6K9gkfo8nPswmw+VYFViZCd3VvO45vUeFHIpnJ
bWsxHJS4w4JGh7e8614r4H7/XVClqttY9zjg5nHdmZDscD7SeDeFPQYylQKBgC9b
g2QqKR61D7CSvuNXSgVIiBwUaxIAS5w1naIrklcw50NkanPPm1DzOZ7aIECKoYvL
/ZAQ9HWC+kxC+26g5hl5Zj6KmlLdQSxy0QGZLKBAYsj6+PqZhEhfHyGUlVmGe/T6
OI2YV1Tv2A2r16wqNJakAuBHpiSCkaJ74Wi4sBeRAoGAKcDxa9O5Tthgc6ZWB03R
3EW7Qgj10eWlSzwcA9eWF908KlY8sDS16Z32MyMkZQF9W0D8CMnLG9QNyrY7n6qB
HKL9VBa5RJMLpPCFbUdZ3aR8R+QjvamqtNuDkXGNsc6QvJ+ZMtueInJLTfV2kQys
XtaHNFy3Ol5bd3xotnCcmPA=
-----END PRIVATE KEY-----
"""
client_email                = "barnswallowfantasy@barnswallowfantasy.iam.gserviceaccount.com"
client_id                   = "103161331224806667739"
auth_uri                    = "https://accounts.google.com/o/oauth2/auth"
token_uri                   = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url        = "https://www.googleapis.com/robot/v1/metadata/x509/barnswallowfantasy%40barnswallowfantasy.iam.gserviceaccount.com"
